In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as npy
import datetime as dt
import matplotlib.dates as mdates

Provisional_COVID_Deaths = pd.read_csv("Datasets/Provisional_COVID-19_Deaths_by_Sex_and_Age.csv")
prov = pd.DataFrame(Provisional_COVID_Deaths)
State_Populations = pd.read_csv("Datasets/StatePops.csv")
pops = pd.DataFrame(State_Populations)

#source: https://worldpopulationreview.com/state-rankings/state-densities
State_Densities = pd.read_csv("Datasets/StatePopDense.csv")
dens = pd.DataFrame(State_Densities)
#print(prov)

In [5]:
#select only All Ages, All Sexes, and By Total in specified columns
all_ages = prov.loc[(prov['Age Group'] == 'All Ages') & (prov['Sex'] == 'All Sexes') & (prov['Group'] == 'By Total')]
#all_ages

In [6]:
#drop nonstates
all_ages.drop(all_ages[all_ages['State'] == 'United States'].index, inplace = True)
all_ages.drop(all_ages[all_ages['State'] == 'District of Columbia'].index, inplace = True)
all_ages.drop(all_ages[all_ages['State'] == 'Puerto Rico'].index, inplace = True)

all_ages = all_ages.replace('New York City', 'New York')

unique = pd.unique(all_ages['State'])

#print(len(unique))
#print(unique)

/var/folders/f0/kd1cqcg106vfwc3f9zf4dhf80000gn/T/ipykernel_18000/2485212810.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_ages.drop(all_ages[all_ages['State'] == 'United States'].index, inplace = True)
/var/folders/f0/kd1cqcg106vfwc3f9zf4dhf80000gn/T/ipykernel_18000/2485212810.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_ages.drop(all_ages[all_ages['State'] == 'District of Columbia'].index, inplace = True)
/var/folders/f0/kd1cqcg106vfwc3f9zf4dhf80000gn/T/ipykernel_18000/2485212810.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_ages.drop(all_ages[all_ages['State'] == 'Puerto Rico'].index, inplace = True)

In [7]:
#reset indices
all_ages.reset_index(drop=True, inplace=True)
#all_ages

In [8]:
#remove unused columns leaving only Data As Of, State, COVID-19 Deaths, and Total Deaths
cleaned2 = all_ages[['Data As Of', 'State', 'COVID-19 Deaths', 'Total Deaths']]
cleaned2

    Data As Of           State  COVID-19 Deaths  Total Deaths
0   11/09/2022         Alabama          20338.0      179876.0
1   11/09/2022          Alaska           1401.0       15288.0
2   11/09/2022         Arizona          28466.0      220804.0
3   11/09/2022        Arkansas          11845.0      108595.0
4   11/09/2022      California         101418.0      908974.0
5   11/09/2022        Colorado          14176.0      134984.0
6   11/09/2022     Connecticut          11629.0      100252.0
7   11/09/2022        Delaware           3143.0       31402.0
8   11/09/2022         Florida          76249.0      708072.0
9   11/09/2022         Georgia          34356.0      297589.0
10  11/09/2022          Hawaii           1670.0       35406.0
11  11/09/2022           Idaho           5297.0       48749.0
12  11/09/2022        Illinois          36373.0      347327.0
13  11/09/2022         Indiana          25173.0      219387.0
14  11/09/2022            Iowa          10243.0       96923.0
15  11/09/2022          Kansas           9459.0       87201.0
16  11/09/2022        Kentucky          18366.0      160927.0
17  11/09/2022       Louisiana          16798.0      154366.0
18  11/09/2022           Maine           2825.0       46913.0
19  11/09/2022        Maryland          16663.0      162448.0
20  11/09/2022   Massachusetts          19564.0      185526.0
21  11/09/2022        Michigan          34366.0      320503.0
22  11/09/2022       Minnesota          13859.0      144581.0
23  11/09/2022     Mississippi          14031.0      109637.0
24  11/09/2022        Missouri          21839.0      211367.0
25  11/09/2022         Montana           3739.0       34339.0
26  11/09/2022        Nebraska           5262.0       53823.0
27  11/09/2022          Nevada          11599.0       91256.0
28  11/09/2022   New Hampshire           2735.0       39212.0
29  11/09/2022      New Jersey          33588.0      245900.0
30  11/09/2022      New Mexico           8277.0       65651.0
31  11/09/2022        New York          38910.0      327824.0
32  11/09/2022        New York          36392.0      195585.0
33  11/09/2022  North Carolina          31523.0      319922.0
34  11/09/2022    North Dakota           2934.0       23146.0
35  11/09/2022            Ohio          46202.0      402407.0
36  11/09/2022        Oklahoma          17168.0      133118.0
37  11/09/2022          Oregon           8223.0      120369.0
38  11/09/2022    Pennsylvania          49263.0      433825.0
39  11/09/2022    Rhode Island           3818.0       32840.0
40  11/09/2022  South Carolina          19363.0      173946.0
41  11/09/2022    South Dakota           3240.0       26567.0
42  11/09/2022       Tennessee          28118.0      255808.0
43  11/09/2022           Texas          99459.0      723051.0
44  11/09/2022            Utah           5471.0       64135.0
45  11/09/2022         Vermont            783.0       18070.0
46  11/09/2022        Virginia          21274.0      231705.0
47  11/09/2022      Washington          13514.0      187275.0
48  11/09/2022   West Virginia           7625.0       76471.0
49  11/09/2022       Wisconsin          15686.0      172100.0
50  11/09/2022         Wyoming           1721.0       15922.0

In [23]:
#select only state and 2022 population from state populations dataset
pops2 = pops[['state', 'pop2022']]
pops2

             state   pop2022
0       California  39995077
1            Texas  29945493
2          Florida  22085563
3         New York  20365879
4     Pennsylvania  13062764
5         Illinois  12808884
6             Ohio  11852036
7          Georgia  10916760
8   North Carolina  10620168
9         Michigan  10116069
10      New Jersey   9388414
11        Virginia   8757467
12      Washington   7901429
13         Arizona   7303398
14   Massachusetts   7126375
15       Tennessee   7023788
16         Indiana   6845874
17        Maryland   6257958
18        Missouri   6188111
19       Wisconsin   5935064
20        Colorado   5922618
21       Minnesota   5787008
22  South Carolina   5217037
23         Alabama   5073187
24       Louisiana   4682633
25        Kentucky   4539130
26          Oregon   4318492
27        Oklahoma   4000953
28     Connecticut   3612314
29            Utah   3373162
30            Iowa   3219171
31          Nevada   3185426
32        Arkansas   3030646
33     Mississippi   2960075
34          Kansas   2954832
35      New Mexico   2129190
36        Nebraska   1988536
37           Idaho   1893410
38   West Virginia   1781860
39          Hawaii   1474265
40   New Hampshire   1389741
41           Maine   1369159
42    Rhode Island   1106341
43         Montana   1103187
44        Delaware   1008350
45    South Dakota    901165
46    North Dakota    800394
47          Alaska    738023
48         Vermont    646545
49         Wyoming    579495

In [9]:
dens2 = dens[['state', 'pop2022', 'densityMi']]
dens2

             state   pop2022   densityMi
0    Massachusetts   7126375   913.63782
1         Missouri   6188111    90.01936
2      Connecticut   3612314   746.03759
3    West Virginia   1781860    74.12680
4        Minnesota   5787008    72.67645
5          Vermont    646545    70.14701
6          Montana   1103187     7.57964
7         Maryland   6257958   644.68507
8          Arizona   7303398    64.29387
9      Mississippi   2960075    63.08367
10        Oklahoma   4000953    58.32718
11        Arkansas   3030646    58.24245
12            Iowa   3219171    57.63236
13        Colorado   5922618    57.14496
14        Delaware   1008350   517.36788
15         Wyoming    579495     5.96845
16          Oregon   4318492    44.98992
17           Maine   1369159    44.39124
18        New York  20365879   432.15802
19         Florida  22085563   411.85199
20            Utah   3373162    41.05102
21          Kansas   2954832    36.14076
22    Pennsylvania  13062764   291.95101
23            Ohio  11852036   290.05741
24          Nevada   3185426    29.01619
25      California  39995077   256.74242
26        Nebraska   1988536    25.88431
27        Illinois  12808884   230.71172
28          Hawaii   1474265   229.52904
29        Virginia   8757467   221.76417
30           Idaho   1893410    22.91071
31  North Carolina  10620168   218.44107
32         Indiana   6845874   191.08675
33         Georgia  10916760   189.81378
34        Michigan  10116069   178.92197
35  South Carolina   5217037   173.54835
36       Tennessee   7023788   170.33559
37      New Mexico   2129190    17.55338
38   New Hampshire   1389741   155.22629
39      New Jersey   9388414  1276.64047
40      Washington   7901429   118.89715
41        Kentucky   4539130   114.95543
42           Texas  29945493   114.63179
43    South Dakota    901165    11.88700
44    North Dakota    800394    11.59974
45       Wisconsin   5935064   109.58795
46       Louisiana   4682633   108.38425
47    Rhode Island   1106341  1069.96228
48         Alabama   5073187   100.17153
49          Alaska    738023     1.29332

In [10]:
#merge covid deaths dataset with state populations dataset
new = pd.merge(cleaned2, dens2, how='inner', left_on = 'State', right_on = 'state')
new.drop(columns=['state'], inplace=True)
new = new.groupby('State').sum()
new

/var/folders/f0/kd1cqcg106vfwc3f9zf4dhf80000gn/T/ipykernel_18000/3833923099.py:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  new = new.groupby('State').sum()

                COVID-19 Deaths  Total Deaths   pop2022   densityMi
State
Alabama                 20338.0      179876.0   5073187   100.17153
Alaska                   1401.0       15288.0    738023     1.29332
Arizona                 28466.0      220804.0   7303398    64.29387
Arkansas                11845.0      108595.0   3030646    58.24245
California             101418.0      908974.0  39995077   256.74242
Colorado                14176.0      134984.0   5922618    57.14496
Connecticut             11629.0      100252.0   3612314   746.03759
Delaware                 3143.0       31402.0   1008350   517.36788
Florida                 76249.0      708072.0  22085563   411.85199
Georgia                 34356.0      297589.0  10916760   189.81378
Hawaii                   1670.0       35406.0   1474265   229.52904
Idaho                    5297.0       48749.0   1893410    22.91071
Illinois                36373.0      347327.0  12808884   230.71172
Indiana                 25173.0      219387.0   6845874   191.08675
Iowa                    10243.0       96923.0   3219171    57.63236
Kansas                   9459.0       87201.0   2954832    36.14076
Kentucky                18366.0      160927.0   4539130   114.95543
Louisiana               16798.0      154366.0   4682633   108.38425
Maine                    2825.0       46913.0   1369159    44.39124
Maryland                16663.0      162448.0   6257958   644.68507
Massachusetts           19564.0      185526.0   7126375   913.63782
Michigan                34366.0      320503.0  10116069   178.92197
Minnesota               13859.0      144581.0   5787008    72.67645
Mississippi             14031.0      109637.0   2960075    63.08367
Missouri                21839.0      211367.0   6188111    90.01936
Montana                  3739.0       34339.0   1103187     7.57964
Nebraska                 5262.0       53823.0   1988536    25.88431
Nevada                  11599.0       91256.0   3185426    29.01619
New Hampshire            2735.0       39212.0   1389741   155.22629
New Jersey              33588.0      245900.0   9388414  1276.64047
New Mexico               8277.0       65651.0   2129190    17.55338
New York                75302.0      523409.0  40731758   864.31604
North Carolina          31523.0      319922.0  10620168   218.44107
North Dakota             2934.0       23146.0    800394    11.59974
Ohio                    46202.0      402407.0  11852036   290.05741
Oklahoma                17168.0      133118.0   4000953    58.32718
Oregon                   8223.0      120369.0   4318492    44.98992
Pennsylvania            49263.0      433825.0  13062764   291.95101
Rhode Island             3818.0       32840.0   1106341  1069.96228
South Carolina          19363.0      173946.0   5217037   173.54835
South Dakota             3240.0       26567.0    901165    11.88700
Tennessee               28118.0      255808.0   7023788   170.33559
Texas                   99459.0      723051.0  29945493   114.63179
Utah                     5471.0       64135.0   3373162    41.05102
Vermont                   783.0       18070.0    646545    70.14701
Virginia                21274.0      231705.0   8757467   221.76417
Washington              13514.0      187275.0   7901429   118.89715
West Virginia            7625.0       76471.0   1781860    74.12680
Wisconsin               15686.0      172100.0   5935064   109.58795
Wyoming                  1721.0       15922.0    579495     5.96845

In [27]:
with open('covdeaths_statepops.txt', 'w') as csv_file:
    new.to_csv(path_or_buf=csv_file)