In [69]:
import pandas as pd

In [70]:
df = pd.read_csv('Datasets\COVID-19_Hospital_Data_from_the_National_Hospital_Care_Survey.csv')
df

,Figure,Setting,Indicator,Group,Subgroup,Time,Start_Time,End_Time,Value,Measure
0,0,ED,NaN,NaN,NaN,12,03/18/2020,03/24/2020,32342.0,Number of encounters
1,0,ED,NaN,NaN,NaN,13,03/25/2020,03/31/2020,26325.0,Number of encounters
2,0,ED,NaN,NaN,NaN,14,04/01/2020,04/07/2020,22141.0,Number of encounters
3,0,ED,NaN,NaN,NaN,15,04/08/2020,04/14/2020,20933.0,Number of encounters
4,0,ED,NaN,NaN,NaN,16,04/15/2020,04/21/2020,20935.0,Number of encounters
...,...,...,...,...,...,...,...,...,...,...
28931,8,IP,Confirmed COVID-19 with pneumonia,Total,Total,139,08/24/2022,08/30/2022,26.3,Percent
28932,8,IP,Confirmed COVID-19 with pneumonia,Total,Total,140,08/31/2022,09/06/2022,23.5,Percent
28933,8,IP,Confirmed COVID-19 with pneumonia,Total,Total,141,09/07/2022,09/13/2022,20.6,Percent
28934,8,IP,Confirmed COVID-19 with pneumonia,Total,Total,142,09/14/2022,09/20/2022,26.8,Percent
28935,8,IP,Confirmed COVID-19 with pneumonia,Total,Total,143,09/21/2022,09/27/2022,20.4,Percent

In [71]:
df = df[['Group', 'Subgroup', 'Value', 'Start_Time','Measure']]

In [72]:
df = df[df['Measure'] == 'Average length of stay (days)']

In [73]:
df1 = df[df['Group'] == 'Discharge Status']
df = df[df['Group'] == 'Age']

In [74]:
df = df.reset_index()
df = df.drop('index', axis=1)
df = df.drop('Measure', axis=1)

df1 = df1.reset_index()
df1 = df1.drop('index', axis=1)
df1 = df1.drop('Measure', axis=1)

In [75]:
df
df.to_csv('Datasets/AvgLengthOfStaysAge.csv')

In [76]:
df1
df1.to_csv('Datasets/AvgLengthOfStaysDischargeStatus.csv')