In [4]:
import pandas as pd
import matplotlib.pyplot as plt

covid = pd.read_csv("Archive__COVID-19_Vaccination_Demographic_Trends_by_Report_Date__National.csv")
covid

,Date,Demographic_category,Administered_Dose1,Series_Complete_Yes,Administered_Dose1_pct_agegroup,Series_Complete_Pop_pct_agegroup
0,08/15/2021 12:00:00 AM,Age_unknown,21642,4921,0.0,0.0
1,11/17/2021 12:00:00 AM,Age_known,210004814,179876860,0.0,0.0
2,11/17/2021 12:00:00 AM,Age_unknown,23646,5596,0.0,0.0
3,11/17/2021 12:00:00 AM,Ages_<12yrs,1946263,130400,4.5,0.3
4,11/17/2021 12:00:00 AM,Ages_<18yrs,15658033,11730333,23.6,17.7
...,...,...,...,...,...,...
9443,12/14/2020 12:00:00 AM,Race_eth_known,0,0,0.0,0.0
9444,12/13/2020 12:00:00 AM,Sex_known,0,0,0.0,0.0
9445,12/13/2020 12:00:00 AM,Race_eth_known,0,0,0.0,0.0
9446,12/13/2020 12:00:00 AM,US,0,0,0.0,0.0
9447,12/13/2020 12:00:00 AM,Age_known,0,0,0.0,0.0

In [7]:
covid.head(18)

,Date,Demographic_category,Administered_Dose1,Series_Complete_Yes,Administered_Dose1_pct_agegroup,Series_Complete_Pop_pct_agegroup
0,08/15/2021 12:00:00 AM,Age_unknown,21642,4921,0.0,0.0
1,11/17/2021 12:00:00 AM,Age_known,210004814,179876860,0.0,0.0
2,11/17/2021 12:00:00 AM,Age_unknown,23646,5596,0.0,0.0
3,11/17/2021 12:00:00 AM,Ages_<12yrs,1946263,130400,4.5,0.3
4,11/17/2021 12:00:00 AM,Ages_<18yrs,15658033,11730333,23.6,17.7
5,11/17/2021 12:00:00 AM,Ages_12-15_yrs,8831424,7391323,58.0,48.5
6,11/17/2021 12:00:00 AM,Ages_16-17_yrs,4880346,4208610,64.5,55.6
7,11/17/2021 12:00:00 AM,Ages_18-24_yrs,18773084,15733822,67.6,56.7
8,11/17/2021 12:00:00 AM,Ages_18-29_yrs,32874378,27639829,66.6,56.0
9,11/17/2021 12:00:00 AM,Ages_25-39_yrs,44240975,37784532,71.3,60.9
10,11/17/2021 12:00:00 AM,Ages_30-39_yrs,30139681,25878525,74.4,63.9
11,11/17/2021 12:00:00 AM,Ages_40-49_yrs,29393932,25633503,79.3,69.2
12,11/17/2021 12:00:00 AM,Ages_50-64_yrs,50830993,44861629,86.6,76.4
13,11/17/2021 12:00:00 AM,Ages_65-74_yrs,30385827,26270811,99.9,88.6
14,11/17/2021 12:00:00 AM,Ages_75+_yrs,20721970,17862230,96.8,83.4
15,11/17/2021 12:00:00 AM,Race_eth_Hispanic,24501092,21750585,46.9,41.6
16,11/17/2021 12:00:00 AM,Race_eth_known,143591924,129478421,0.0,0.0
17,11/17/2021 12:00:00 AM,Race_eth_NHAIAN,1410970,1187796,60.3,50.7