In [1]:
import pandas as pd
import datetime
from sodapy import Socrata

In [5]:
client = Socrata("data.cdc.gov", None)
results = client.get("wgvr-7mvz", limit=1000000)


df = pd.DataFrame.from_records(results)
df

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

,uniqueid,eventname,state,distname,districtncesid,distweb,type,epi_week,dateclosure,datereopened,schoolname,schoolncesid,schoolweb
0,AK202010001D,COVID-19,AK,ALASKA GATEWAY SCHOOL DISTRICT,0200050,http://www.agsd.us,D,12,2020-03-16T00:00:00.000,NaN,NaN,NaN,NaN
1,AK202010002D,COVID-19,AK,ALEUTIAN REGION SCHOOL DISTRICT,0200010,http://www.aleutregion.org,D,12,2020-03-16T00:00:00.000,NaN,NaN,NaN,NaN
2,AK202010003D,COVID-19,AK,ALEUTIANS EAST BOROUGH SCHOOL DISTRICT,0200007,http://www.aebsd.org,D,12,2020-03-16T00:00:00.000,NaN,NaN,NaN,NaN
3,AK202010004D,COVID-19,AK,ANCHORAGE SCHOOL DISTRICT,0200180,http://www.asdk12.org,D,12,2020-03-16T00:00:00.000,NaN,NaN,NaN,NaN
4,AK202010005D,COVID-19,AK,ANNETTE ISLAND SCHOOL DISTRICT,0200525,http://www.aisdk12.org,D,12,2020-03-16T00:00:00.000,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16991,WA202090052S,COVID-19,WA,NaN,5307710,NaN,I,11,2020-03-11T00:00:00.000,NaN,Cleveland High School STEM,530771001150,NaN
16992,WA202090053S,COVID-19,WA,NaN,5305430,NaN,I,11,2020-03-10T00:00:00.000,NaN,Mariner High School,530543000818,NaN
16993,WA202090054S,COVID-19,WA,NaN,5305430,NaN,I,11,2020-03-10T00:00:00.000,NaN,Challenger Elementary,530543002128,NaN
16994,WA202090055S,COVID-19,WA,NaN,5900176,NaN,I,11,2020-03-10T00:00:00.000,2020-03-11T00:00:00.000,Lummi Elementary,590017600124,http://www.lummi-k12.org/
16995,WA202090056S,COVID-19,WA,NaN,5900115,NaN,I,11,2020-03-10T00:00:00.000,2020-03-11T00:00:00.000,Lummi High School,590011500123,http://www.lummi-k12.org/

In [9]:
dateClosure = df['dateclosure'].str.slice(stop=10)
df['dtClosure'] = pd.to_datetime(dateClosure, format='%Y/%m/%d')
df['epochClosure'] = df['dtClosure'].apply(lambda x: int(x.timestamp()))
df

,uniqueid,eventname,state,distname,districtncesid,distweb,type,epi_week,dateclosure,datereopened,schoolname,schoolncesid,schoolweb,dtClosure,epochClosure
0,AK202010001D,COVID-19,AK,ALASKA GATEWAY SCHOOL DISTRICT,0200050,http://www.agsd.us,D,12,2020-03-16T00:00:00.000,NaN,NaN,NaN,NaN,2020-03-16,1584316800
1,AK202010002D,COVID-19,AK,ALEUTIAN REGION SCHOOL DISTRICT,0200010,http://www.aleutregion.org,D,12,2020-03-16T00:00:00.000,NaN,NaN,NaN,NaN,2020-03-16,1584316800
2,AK202010003D,COVID-19,AK,ALEUTIANS EAST BOROUGH SCHOOL DISTRICT,0200007,http://www.aebsd.org,D,12,2020-03-16T00:00:00.000,NaN,NaN,NaN,NaN,2020-03-16,1584316800
3,AK202010004D,COVID-19,AK,ANCHORAGE SCHOOL DISTRICT,0200180,http://www.asdk12.org,D,12,2020-03-16T00:00:00.000,NaN,NaN,NaN,NaN,2020-03-16,1584316800
4,AK202010005D,COVID-19,AK,ANNETTE ISLAND SCHOOL DISTRICT,0200525,http://www.aisdk12.org,D,12,2020-03-16T00:00:00.000,NaN,NaN,NaN,NaN,2020-03-16,1584316800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16991,WA202090052S,COVID-19,WA,NaN,5307710,NaN,I,11,2020-03-11T00:00:00.000,NaN,Cleveland High School STEM,530771001150,NaN,2020-03-11,1583884800
16992,WA202090053S,COVID-19,WA,NaN,5305430,NaN,I,11,2020-03-10T00:00:00.000,NaN,Mariner High School,530543000818,NaN,2020-03-10,1583798400
16993,WA202090054S,COVID-19,WA,NaN,5305430,NaN,I,11,2020-03-10T00:00:00.000,NaN,Challenger Elementary,530543002128,NaN,2020-03-10,1583798400
16994,WA202090055S,COVID-19,WA,NaN,5900176,NaN,I,11,2020-03-10T00:00:00.000,2020-03-11T00:00:00.000,Lummi Elementary,590017600124,http://www.lummi-k12.org/,2020-03-10,1583798400
16995,WA202090056S,COVID-19,WA,NaN,5900115,NaN,I,11,2020-03-10T00:00:00.000,2020-03-11T00:00:00.000,Lummi High School,590011500123,http://www.lummi-k12.org/,2020-03-10,1583798400

In [11]:
dfmeans = df.groupby(['state']).mean()
dfmeans

C:\Users\trans\AppData\Local\Temp\ipykernel_16944\276285196.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  dfmeans = df.groupby(['state']).mean()

       epochClosure
state
AK     1.584317e+09
AL     1.584576e+09
AR     1.584363e+09
AZ     1.584316e+09
CA     1.584392e+09
CO     1.584554e+09
CT     1.584369e+09
DC     1.584256e+09
DE     1.584298e+09
FL     1.584312e+09
GA     1.584356e+09
HI     1.584922e+09
IA     1.584374e+09
ID     1.584486e+09
IL     1.584399e+09
IN     1.584639e+09
KS     1.584445e+09
KY     1.584306e+09
LA     1.584315e+09
MA     1.584362e+09
MD     1.584291e+09
ME     1.584348e+09
MI     1.584277e+09
MN     1.584486e+09
MO     1.584525e+09
MS     1.584362e+09
MT     1.584317e+09
NC     1.584317e+09
ND     1.584317e+09
NE     1.584548e+09
NH     1.584300e+09
NJ     1.584450e+09
NM     1.584317e+09
NV     1.584276e+09
NY     1.584426e+09
OH     1.584396e+09
OK     1.584403e+09
OR     1.584310e+09
PA     1.584299e+09
RI     1.584279e+09
SC     1.584317e+09
SD     1.584314e+09
TN     1.584633e+09
TX     1.584755e+09
UT     1.584317e+09
VA     1.584314e+09
VT     1.584474e+09
WA     1.584280e+09
WI     1.584488e+09
WV     1.584317e+09
WY     1.584400e+09

In [13]:
dfmeans['ClosureDate'] = pd.to_datetime(dfmeans['epochClosure'], unit='s')
dfmeans = dfmeans.sort_values(by=['epochClosure'])
dfmeans = dfmeans.reset_index()
dfFinal = dfmeans[['state', 'ClosureDate']]
dfFinal['ClosureDate'] = dfFinal['ClosureDate'].apply(lambda x: x.strftime('%Y-%m-%d'))
dfFinal

C:\Users\trans\AppData\Local\Temp\ipykernel_16944\520844355.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfFinal['ClosureDate'] = dfFinal['ClosureDate'].apply(lambda x: x.strftime('%Y-%m-%d'))

   state ClosureDate
0     DC  2020-03-15
1     NV  2020-03-15
2     MI  2020-03-15
3     RI  2020-03-15
4     WA  2020-03-15
5     MD  2020-03-15
6     DE  2020-03-15
7     PA  2020-03-15
8     NH  2020-03-15
9     KY  2020-03-15
10    OR  2020-03-15
11    FL  2020-03-15
12    SD  2020-03-15
13    VA  2020-03-15
14    LA  2020-03-15
15    AZ  2020-03-15
16    ND  2020-03-16
17    NC  2020-03-16
18    AK  2020-03-16
19    WV  2020-03-16
20    SC  2020-03-16
21    UT  2020-03-16
22    NM  2020-03-16
23    MT  2020-03-16
24    ME  2020-03-16
25    GA  2020-03-16
26    MA  2020-03-16
27    MS  2020-03-16
28    AR  2020-03-16
29    CT  2020-03-16
30    IA  2020-03-16
31    CA  2020-03-16
32    OH  2020-03-16
33    IL  2020-03-16
34    WY  2020-03-16
35    OK  2020-03-17
36    NY  2020-03-17
37    KS  2020-03-17
38    NJ  2020-03-17
39    VT  2020-03-17
40    MN  2020-03-17
41    ID  2020-03-17
42    WI  2020-03-17
43    MO  2020-03-18
44    NE  2020-03-18
45    CO  2020-03-18
46    AL  2020-03-19
47    TN  2020-03-19
48    IN  2020-03-19
49    TX  2020-03-21
50    HI  2020-03-23

In [ ]:
dfFinal.to_csv('AverageSchoolClosure.csv')