In [68]:
import pandas as pd
import numpy as npy
from pathlib import Path  

WorkedOnSite = pd.read_csv("Datasets/WorkedOnsiteWeeks34-45.csv")
WorkedOnSite

,"Worked Onsite at a Workplace, Household Pulse Survey",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Adults in households where someone worked onsi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,Total Worked Onsite at a Workplace,NaN,Percent Worked Onsite at a Workplace,NaN,NaN,NaN
2,Area,Week,Number,Margin of Error +/-,Percent,Percent Margin of Error +/-,Measure Universe,Total Population age 18+
3,United States,"45 - April 27 - May 9, 2022",135909004,1330154,60.3,0.5,225486157,252481011
4,United States,"44 - March 30 - April 11, 2022",134351234,1740943,59.7,0.7,225203549,252481011
...,...,...,...,...,...,...,...,...
805,"Riverside-San Bernardino-Ontario, CA Metro Area","34 - July 21 - August 2, 2021",2016813,243973,56.2,5.3,3586599,4371711
806,"San Francisco-Oakland-Berkeley, CA Metro Area","34 - July 21 - August 2, 2021",1664370,231788,51.3,4.9,3242792,3658670
807,"Seattle-Tacoma-Bellevue, WA Metro Area","34 - July 21 - August 2, 2021",1801785,139761,60.2,3,2992766,3276754
808,"Washington-Arlington-Alexandria, DC-VA-MD-WV M...","34 - July 21 - August 2, 2021",2433602,181002,56.1,2.7,4335074,4677845
809,"Source: U.S. Census Bureau, Household Pulse Su...",NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
#Isolating US and cut the front 2 numbers of each date to get just the week number
WorkedOnSite = WorkedOnSite.iloc[3:]
USwos = WorkedOnSite.iloc[:12]
USwos['Unnamed: 1'] = USwos['Unnamed: 1'].str[:2]
#USwos
filepath = Path('Datasets/USOnsite.csv')  
filepath.parent.mkdir(parents=True, exist_ok=True)  
USwos.to_csv(filepath)

/var/folders/_v/knkk6sdx7pl2v07sl83qvm680000gn/T/ipykernel_12579/2855576755.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  USwos['Unnamed: 1'] = USwos['Unnamed: 1'].str[:2]

In [ ]:
#Isolating Week45 States
Statewos45 = WorkedOnSite.iloc[13:]
Statewos45 = Statewos45.iloc[:51]
Statewos45.drop([24], inplace=True)
Statewos45

filepath = Path('Datasets/StateOnsite45.csv')      
filepath.parent.mkdir(parents=True, exist_ok=True)  
Statewos45.to_csv(filepath)

In [ ]:
#Isolating Week34 States
Statewos34 = WorkedOnSite.iloc[574:]
Statewos34 = Statewos34.iloc[:51]
Statewos34.drop([585], inplace=True)
Statewos34
  
filepath = Path('Datasets/StateOnsite34.csv')  
filepath.parent.mkdir(parents=True, exist_ok=True)  
Statewos34.to_csv(filepath)