In [14]:
import pandas as pd
import matplotlib.pyplot as plt

In [15]:
teleAccess = pd.read_csv('Datasets\Access_and_Use_of_Telemedicine_During_COVID-19.csv')
teleAccess.head()

,Round,Indicator,Group,Subgroup,Sample Size,Response,Percent,Standard Error,Suppression,Significant 1,Significant 2
0,1,Provider offers telemedicine,Total,Total,6786.0,Total,100.0,NaN,NaN,NaN,NaN
1,1,Provider offers telemedicine,Total,Total,NaN,Yes,36.6,0.8,NaN,NaN,NaN
2,1,Provider offers telemedicine,Total,Total,NaN,No,46.9,0.8,NaN,NaN,NaN
3,1,Provider offers telemedicine,Total,Total,NaN,Do not know,5.2,0.4,NaN,NaN,NaN
4,1,Provider offers telemedicine,Total,Total,NaN,No usual place of care,11.3,0.7,NaN,NaN,NaN

In [16]:
#drop columns that are not needed
teleAccess.drop(['Round', 'Standard Error', 'Suppression', 'Significant 1', 'Significant 2'], axis=1, inplace=True)
teleAccess

,Indicator,Group,Subgroup,Sample Size,Response,Percent
0,Provider offers telemedicine,Total,Total,6786.0,Total,100.0
1,Provider offers telemedicine,Total,Total,NaN,Yes,36.6
2,Provider offers telemedicine,Total,Total,NaN,No,46.9
3,Provider offers telemedicine,Total,Total,NaN,Do not know,5.2
4,Provider offers telemedicine,Total,Total,NaN,No usual place of care,11.3
...,...,...,...,...,...,...
793,Provider offered telemedicine prior to pandemic,Chronic conditions,Current asthma,118.0,Total,100.0
794,Provider offered telemedicine prior to pandemic,Chronic conditions,Current asthma,NaN,Yes,27.3
795,Provider offered telemedicine prior to pandemic,Chronic conditions,Current asthma,NaN,No,53.0
796,Provider offered telemedicine prior to pandemic,Chronic conditions,Current asthma,NaN,Do not know,NaN
797,Provider offered telemedicine prior to pandemic,Chronic conditions,Current asthma,NaN,No usual place of care,NaN

In [17]:
#convert the data to numeric
teleAccess['Percent'] = pd.to_numeric(teleAccess['Percent'], errors='coerce')
teleAccess

,Indicator,Group,Subgroup,Sample Size,Response,Percent
0,Provider offers telemedicine,Total,Total,6786.0,Total,100.0
1,Provider offers telemedicine,Total,Total,NaN,Yes,36.6
2,Provider offers telemedicine,Total,Total,NaN,No,46.9
3,Provider offers telemedicine,Total,Total,NaN,Do not know,5.2
4,Provider offers telemedicine,Total,Total,NaN,No usual place of care,11.3
...,...,...,...,...,...,...
793,Provider offered telemedicine prior to pandemic,Chronic conditions,Current asthma,118.0,Total,100.0
794,Provider offered telemedicine prior to pandemic,Chronic conditions,Current asthma,NaN,Yes,27.3
795,Provider offered telemedicine prior to pandemic,Chronic conditions,Current asthma,NaN,No,53.0
796,Provider offered telemedicine prior to pandemic,Chronic conditions,Current asthma,NaN,Do not know,NaN
797,Provider offered telemedicine prior to pandemic,Chronic conditions,Current asthma,NaN,No usual place of care,NaN

In [ ]:
#convert to csv
teleAccess.to_csv('Datasets\\teleAccess.csv', index=False)

In [ ]:
#convert to json
teleAccess.to_json('Datasets\\teleAccess.json', orient='records')