In [1]:
import pandas as pd

In [3]:
restaurantDf = pd.read_csv(r"Datasets\U.S._State_and_Territorial_Orders_Closing_and_Reopening_Restaurants_Issued_from_March_11__2020_through_August_15__2021_by_County_by_Day.csv")

C:\Users\trans\AppData\Local\Temp\ipykernel_29260\950475191.py:1: DtypeWarning: Columns (9,15) have mixed types. Specify dtype option on import or set low_memory=False.
  restaurantDf = pd.read_csv(r"Datasets\U.S._State_and_Territorial_Orders_Closing_and_Reopening_Restaurants_Issued_from_March_11__2020_through_August_15__2021_by_County_by_Day.csv")

In [21]:
#restaurantDf
restaurantDf = restaurantDf[restaurantDf.State_Tribe_Territory != "DC"]
restaurantDf = restaurantDf[restaurantDf.State_Tribe_Territory != "MP"]
restaurantDf = restaurantDf[restaurantDf.State_Tribe_Territory != "AS"]
restaurantDf = restaurantDf[restaurantDf.State_Tribe_Territory != "GU"]
restaurantDf = restaurantDf[restaurantDf.State_Tribe_Territory != "PR"]
restaurantDf = restaurantDf[restaurantDf.State_Tribe_Territory != "VI"]

#restaurantDf.State_Tribe_Territory.unique()
#len(restaurantDf.State_Tribe_Territory.unique())
restaurantDf = restaurantDf.rename(columns = {"State_Tribe_Territory":"state"})

In [18]:
stateConverter = pd.read_csv("Datasets\StateConverter.csv")

stateConverter

                   State  Abbrev state
0                Alabama    Ala.    AL
1                 Alaska  Alaska    AK
2                Arizona   Ariz.    AZ
3               Arkansas    Ark.    AR
4             California  Calif.    CA
5               Colorado   Colo.    CO
6            Connecticut   Conn.    CT
7               Delaware    Del.    DE
8   District of Columbia    D.C.    DC
9                Florida    Fla.    FL
10               Georgia     Ga.    GA
11                Hawaii  Hawaii    HI
12                 Idaho   Idaho    ID
13              Illinois    Ill.    IL
14               Indiana    Ind.    IN
15                  Iowa    Iowa    IA
16                Kansas   Kans.    KS
17              Kentucky     Ky.    KY
18             Louisiana     La.    LA
19                 Maine   Maine    ME
20              Maryland     Md.    MD
21         Massachusetts   Mass.    MA
22              Michigan   Mich.    MI
23             Minnesota   Minn.    MN
24           Mississippi   Miss.    MS
25              Missouri     Mo.    MO
26               Montana   Mont.    MT
27              Nebraska   Nebr.    NE
28                Nevada    Nev.    NV
29         New Hampshire    N.H.    NH
30            New Jersey    N.J.    NJ
31            New Mexico    N.M.    NM
32              New York    N.Y.    NY
33        North Carolina    N.C.    NC
34          North Dakota    N.D.    ND
35                  Ohio    Ohio    OH
36              Oklahoma   Okla.    OK
37                Oregon    Ore.    OR
38          Pennsylvania     Pa.    PA
39          Rhode Island    R.I.    RI
40        South Carolina    S.C.    SC
41          South Dakota    S.D.    SD
42             Tennessee   Tenn.    TN
43                 Texas    Tex.    TX
44                  Utah    Utah    UT
45               Vermont     Vt.    VT
46              Virginia     Va.    VA
47            Washington   Wash.    WA
48         West Virginia   W.Va.    WV
49             Wisconsin    Wis.    WI
50               Wyoming    Wyo.    WY

In [22]:
restaurantDf = restaurantDf.merge(stateConverter, on="state")
restaurantDf

,state,County_Name,FIPS_State,FIPS_County,date,Business_Type,Action,order_code,Source_of_Action,URL,Citation,Percent_Capacity_Outdoor,Percent_Capacity_Indoor,Numeric_Capacity_Outdoor,Numeric_Capacity_Indoor,Limited_Open_Outdoor_Only,Limited_Open_General_Indoor,State,Abbrev
0,AL,Autauga County,1,1,3/15/2020,Restaurants,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Alabama,Ala.
1,AL,Autauga County,1,1,3/16/2020,Restaurants,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Alabama,Ala.
2,AL,Autauga County,1,1,3/17/2020,Restaurants,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Alabama,Ala.
3,AL,Autauga County,1,1,3/18/2020,Restaurants,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Alabama,Ala.
4,AL,Autauga County,1,1,3/19/2020,Restaurants,Curbside/carryout/delivery only,5,Official,http://www.alabamapublichealth.gov/legal/asset...,"Ala. Health Order (Apr. 28, 2020)",NaN,NaN,NaN,NaN,NaN,NaN,Alabama,Ala.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1630174,WY,Weston County,56,45,8/11/2021,Restaurants,Authorized to fully reopen,2,NaN,NaN,"Wyo. Press Release (Mar. 12, 2021)",NaN,NaN,NaN,NaN,NaN,NaN,Wyoming,Wyo.
1630175,WY,Weston County,56,45,8/12/2021,Restaurants,Authorized to fully reopen,2,NaN,NaN,"Wyo. Press Release (Mar. 12, 2021)",NaN,NaN,NaN,NaN,NaN,NaN,Wyoming,Wyo.
1630176,WY,Weston County,56,45,8/13/2021,Restaurants,Authorized to fully reopen,2,NaN,NaN,"Wyo. Press Release (Mar. 12, 2021)",NaN,NaN,NaN,NaN,NaN,NaN,Wyoming,Wyo.
1630177,WY,Weston County,56,45,8/14/2021,Restaurants,Authorized to fully reopen,2,NaN,NaN,"Wyo. Press Release (Mar. 12, 2021)",NaN,NaN,NaN,NaN,NaN,NaN,Wyoming,Wyo.
1630178,WY,Weston County,56,45,8/15/2021,Restaurants,Authorized to fully reopen,2,NaN,NaN,"Wyo. Press Release (Mar. 12, 2021)",NaN,NaN,NaN,NaN,NaN,NaN,Wyoming,Wyo.